
<body>
    <div class="container-fluid">
        <div for="login">
            <form action="" method="POST">
                <input type="email" name="email" value="Enter email">
                <input type="password" name="password" value="Enter password">
                <button>Submit</button>
            </form>
            <a href="/admin/admin/signup" class="btn btn-danger">sign up</a>
        </div>

    </div>
</body>